<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-HCFFR5C" name="links.journalpagelink" tests="47" failures="4" timestamp="08 Feb 2020 18:50:41 GMT" time="7.498" errors="0">
  <testcase name="testCheckLinks" time="0.054" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.061" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.052" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.055" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.096" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.060" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.049" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="1.070" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.051" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.054" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.049" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.050" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.363" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.064" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.000" classname="links.journalpagelink">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at links.journalpagelink.testCheckLinks(journalpagelink.java:74)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCheckLinks -->
  <testcase name="testCheckLinks" time="0.048" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.052" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.161" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.052" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.117" classname="links.journalpagelink">
    <failure type="java.lang.AssertionError" message="expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [403]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at links.journalpagelink.testCheckLinks(journalpagelink.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCheckLinks -->
  <testcase name="testCheckLinks" time="0.001" classname="links.journalpagelink">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at links.journalpagelink.testCheckLinks(journalpagelink.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCheckLinks -->
  <testcase name="testCheckLinks" time="0.920" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.047" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="1.083" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.083" classname="links.journalpagelink">
    <failure type="java.lang.AssertionError" message="expected [200] but found [403]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [403]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:652)
at org.testng.Assert.assertEquals(Assert.java:662)
at links.journalpagelink.testCheckLinks(journalpagelink.java:74)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testCheckLinks -->
  <testcase name="testCheckLinks" time="0.050" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.047" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.054" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.088" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.051" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.056" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.053" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.049" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.052" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.233" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.047" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.671" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.059" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.047" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.055" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.047" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.050" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.062" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.314" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.057" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.614" classname="links.journalpagelink"/>
  <testcase name="testCheckLinks" time="0.050" classname="links.journalpagelink"/>
</testsuite> <!-- links.journalpagelink -->
